name: Deploy to DO

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Deploy backend & restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/tripwise-waitlist-server

            git fetch --all
            git reset --hard origin/production

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            npm install
            cat <<EOF > .env
            ${{ secrets.BACKEND_ENV }}
            EOF
            echo "${{ secrets.BACKEND_ENV }}" > .env
            npm run build
            pm2 reload ecosystem.config.js --update-env

            sudo systemctl restart nginx
